services:
  firecrawler:
    build: .
    #image: docker pull ghcr.io/sammcj/firecrawler:latest
    ports:
      - "${PORT:-3002}:${PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped
