name: Build and publish Docker image to GitHub Container Registry

on:
  workflow_dispatch:
  # release:
  #   types: [published]
  # push:
  #   branches:
  #     - main

# cancel previous runs if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      # - uses: actions/checkout@v4
      - name: todo
        run: echo "Github Actions is not yet configured build the container image"
